// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Microsoft.Windows.Globalization
{
    [contractversion(1)]
    apicontract MrtCoreContract{};

    [contract(MrtCoreContract, 1)]
    runtimeclass ApplicationLanguages
    {
        static IVectorView<String> Languages { get; };
        static IVectorView<String> ManifestLanguages { get; };
        static String PrimaryLanguageOverride;
    }

} // namespace Microsoft.Windows.Globalization
